// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DateToTime(arg1:string):Promise<any>;

export function GetNowTime():Promise<any>;

export function TimeToDate(arg1:string):Promise<any>;
