// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DateToTime(arg1) {
  return window['go']['main']['Time']['DateToTime'](arg1);
}

export function GetNowTime() {
  return window['go']['main']['Time']['GetNowTime']();
}

export function TimeToDate(arg1) {
  return window['go']['main']['Time']['TimeToDate'](arg1);
}
